"""Initial

Revision ID: cab1edb602aa
Revises: 
Create Date: 2022-12-10 14:54:18.445241

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'cab1edb602aa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('solution',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hardware_id', sa.String(length=255), nullable=False),
    sa.Column('caption', sa.String(length=255), nullable=False),
    sa.Column('task_id', sa.String(length=36), nullable=False),
    sa.Column('unique_key', sa.Text(), nullable=False),
    sa.Column('solution', sa.Text(), nullable=False),
    sa.Column('valid', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('checked', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("(now() at time zone 'utc')"), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('unique_key')
    )
    op.create_index(op.f('ix_solution_task_id'), 'solution', ['task_id'], unique=False)
    op.create_index('solution_hardware_id_caption', 'solution', ['hardware_id', 'caption'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('solution_hardware_id_caption', table_name='solution')
    op.drop_index(op.f('ix_solution_task_id'), table_name='solution')
    op.drop_table('solution')
    # ### end Alembic commands ###
