"""Initial

Revision ID: b38f6b75d3d1
Revises: 
Create Date: 2022-12-10 12:19:30.559765

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b38f6b75d3d1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('block_height', sa.Integer(), nullable=False),
    sa.Column('epoch_challenge', sa.Text(), nullable=False),
    sa.Column('task_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("(now() at time zone 'utc')"), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_block_height'), 'job', ['block_height'], unique=True)
    op.create_index(op.f('ix_job_task_id'), 'job', ['task_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job_task_id'), table_name='job')
    op.drop_index(op.f('ix_job_block_height'), table_name='job')
    op.drop_table('job')
    # ### end Alembic commands ###
