"""Initial

Revision ID: 2ad79e8b0612
Revises: 
Create Date: 2022-12-10 12:19:30.653098

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ad79e8b0612'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('worker',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ip', sa.String(length=45), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('hardware', sa.Text(), nullable=False),
    sa.Column('hardware_id', sa.String(length=255), nullable=False),
    sa.Column('caption', sa.String(length=255), nullable=False),
    sa.Column('connected_at', sa.DateTime(), nullable=False),
    sa.Column('disconnected_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_worker_address'), 'worker', ['address'], unique=False)
    op.create_index(op.f('ix_worker_ip'), 'worker', ['ip'], unique=False)
    op.create_index('worker_hardware_id_caption', 'worker', ['hardware_id', 'caption'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('worker_hardware_id_caption', table_name='worker')
    op.drop_index(op.f('ix_worker_ip'), table_name='worker')
    op.drop_index(op.f('ix_worker_address'), table_name='worker')
    op.drop_table('worker')
    # ### end Alembic commands ###
